const blogsData = [
  {
    id: 1,
    img: "https://images-saboomaruti-in.s3.ap-south-1.amazonaws.com/saboomaruti/blogScreen/1.webp",
    title: "TV HYBIZTV HD",
    subTitle: "From Luna to Maruti - How Vinay Saboo built his business",
    href: "https://www.youtube.com/watch?v=xzxj3rTLi10",
    desc: "Today, RKS Saboo has 4 Arena, 2 Nexa showrooms and 7 workshops spread across the twin cities of Hyderabad and Secunderabad.",
  },
  {
    id: 2,
    img: "https://images-saboomaruti-in.s3.ap-south-1.amazonaws.com/saboomaruti/blogScreen/2.webp",
    title: "MONEYCONTROL NEWS",
    subTitle: "2021 Maruti Suzuki Swift review: Should you buy it?",
    href: "https://www.moneycontrol.com/news/technology/auto/2021-maruti-suzuki-swift-review-should-you-buy-it-6681491.html",
    desc: "To deal with a rise in various input costs, India's leading automobile manufacturer Maruti Suzuki India Ltd will increase prices for different car models from April.",
  },
  {
    id: 3,
    img: "https://images-saboomaruti-in.s3.ap-south-1.amazonaws.com/saboomaruti/blogScreen/3.webp",
    title: "News Telanganatoday",
    subTitle: "Md Mahmood Ali, Vinay Saboo, CMD - Saboo RKS, Tanay Saboo, NK Patel, directors, Saboo RKS Motor, and Mozzam, TSM, Maruti Suzuki India.",
    href: "/",
    desc: " Maruti Suzuki’s stylish mini SUV S-Presso launched at Saboo RKS. The new vehicle S-Presso was launched at Saboo RKS Somajiguda",
  },
  {
    id: 4,
    img: "https://images-saboomaruti-in.s3.ap-south-1.amazonaws.com/saboomaruti/blogScreen/4.webp",
    title: "MONEYCONTROL NEWS",
    subTitle: "Maruti Suzuki India to hike prices of cars again from April 2021",
    href: "https://www.moneycontrol.com/news/automobile/maruti-suzuki-india-to-hike-prices-of-cars-again-from-april-2021-6678041.html",
    desc: "To deal with a rise in various input costs, India's leading automobile manufacturer Maruti Suzuki India Ltd will increase prices for different car models from April.",
  },
  {
    id: 5,
    img: "https://images-saboomaruti-in.s3.ap-south-1.amazonaws.com/saboomaruti/blogScreen/5.webp",
    title: "Facebook",
    subTitle: "#MarutiSuzuki #Bs-6 #MarutiPetrolCars #SabooMaruti #ThinkMarutiThinkSaboo",
    href: "https://www.facebook.com/saboomaruti/photos/a.735425553239179/3193521747429535/?type=3&theater",
    desc: "Schoose to be the best, explore our driving school, with customised driving lessons from certified and highly trained instructors. Make the right decision.",
  },
  {
    id: 6,
    img: "https://images-saboomaruti-in.s3.ap-south-1.amazonaws.com/saboomaruti/blogScreen/6.webp",
    title: "Twitter",
    subTitle: "Live-up the drive like never before!",
    href: "https://twitter.com/saboorksmaruti/status/1310456648117317632",
    desc: "SmartPlay studio, centrally located power window switches, auto gear shift, rear parking assist sensor, equipped with dual airbags.",
  },
  {
    id: 7,
    img: "https://images-saboomaruti-in.s3.ap-south-1.amazonaws.com/saboomaruti/blogScreen/7.webp",
    title: "youtube",
    subTitle: "Saboo RKS | Fully Sanitized Vehicle I Home Delivery | We are Safe and Ready",
    href: "https://www.youtube.com/watch?v=0KCUR1BToDQ",
    desc: "We remain committed to serving our customers while keeping the health and safety front and center. As always, we have and will continue to enable customers to transact from the comfort and safety of their homes. ",
  },
  {
    id: 8,
    img: "https://images-saboomaruti-in.s3.ap-south-1.amazonaws.com/saboomaruti/blogScreen/8.webp",
    title: "News thehansindia",
    subTitle: "Gaadi Delivered",
    href: "https://www.thehansindia.com/posts/index/Hans/2015-10-29/Gaadi-delivered/183270",
    desc: "Post the launch, RKS Saboo deliovered its first Maruti Suzuki Baleno to customer G Radhika. The key was handed over by Sandeep Kumar Sultania, IAS Transport Commissioner and CMD Vinay Saboo at Nexa Jubilee showroom of Saboo RKS group.",
  },
];

export { blogsData };
